baseURL = "https://exocytosis.netlify.com/"
title = "Exocytosis"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""
theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "A personal blogsite"
title404 = "Oops! Page not found."

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Naomi Penfold"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false

# [params.opengraph.facebook]
# admins = [] # array of Facebook IDs
# appID = ""
# pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
# codepen = ""
email = "naomipenfold@gmail.com"
# facebook = ""
github = "npscience"
instagram = "_npscience"
linkedin = "naomipenfold"
twitter = "npscience"
# telegram = ""

[params.social.config]
platforms = ["github","twitter","instagram","email","linkedin"]
# other platforms: "facebook","codepen","telegram"

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = ["blog", "TIL"]
weight = -10
identifier = ["blog","TIL"]
url = ""

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
